{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "harness-gitops-agent-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-gitops-agent-controller.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "harness-gitops-agent-controller.selectorLabels" . | nindent 6 }}
{{- end }}
