//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsAgent) DeepCopyInto(out *HarnessGitopsAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsAgent.
func (in *HarnessGitopsAgent) DeepCopy() *HarnessGitopsAgent {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessGitopsAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsAgentList) DeepCopyInto(out *HarnessGitopsAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HarnessGitopsAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsAgentList.
func (in *HarnessGitopsAgentList) DeepCopy() *HarnessGitopsAgentList {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessGitopsAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsAgentReference) DeepCopyInto(out *HarnessGitopsAgentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsAgentReference.
func (in *HarnessGitopsAgentReference) DeepCopy() *HarnessGitopsAgentReference {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsAgentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsAgentSpec) DeepCopyInto(out *HarnessGitopsAgentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsAgentSpec.
func (in *HarnessGitopsAgentSpec) DeepCopy() *HarnessGitopsAgentSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsAgentStatus) DeepCopyInto(out *HarnessGitopsAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsAgentStatus.
func (in *HarnessGitopsAgentStatus) DeepCopy() *HarnessGitopsAgentStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMapping) DeepCopyInto(out *HarnessGitopsProjectMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMapping.
func (in *HarnessGitopsProjectMapping) DeepCopy() *HarnessGitopsProjectMapping {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessGitopsProjectMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingAgentStatus) DeepCopyInto(out *HarnessGitopsProjectMappingAgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingAgentStatus.
func (in *HarnessGitopsProjectMappingAgentStatus) DeepCopy() *HarnessGitopsProjectMappingAgentStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingList) DeepCopyInto(out *HarnessGitopsProjectMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HarnessGitopsProjectMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingList.
func (in *HarnessGitopsProjectMappingList) DeepCopy() *HarnessGitopsProjectMappingList {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessGitopsProjectMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingRemoteStatus) DeepCopyInto(out *HarnessGitopsProjectMappingRemoteStatus) {
	*out = *in
	out.Agent = in.Agent
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingRemoteStatus.
func (in *HarnessGitopsProjectMappingRemoteStatus) DeepCopy() *HarnessGitopsProjectMappingRemoteStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingRemoteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingSpec) DeepCopyInto(out *HarnessGitopsProjectMappingSpec) {
	*out = *in
	out.AgentRef = in.AgentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingSpec.
func (in *HarnessGitopsProjectMappingSpec) DeepCopy() *HarnessGitopsProjectMappingSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingStatus) DeepCopyInto(out *HarnessGitopsProjectMappingStatus) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(HarnessGitopsProjectMappingRemoteStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingStatus.
func (in *HarnessGitopsProjectMappingStatus) DeepCopy() *HarnessGitopsProjectMappingStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessGitopsProjectMappingTargetStatus) DeepCopyInto(out *HarnessGitopsProjectMappingTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessGitopsProjectMappingTargetStatus.
func (in *HarnessGitopsProjectMappingTargetStatus) DeepCopy() *HarnessGitopsProjectMappingTargetStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessGitopsProjectMappingTargetStatus)
	in.DeepCopyInto(out)
	return out
}
