apiVersion: infrastructure.kandylis.co.uk/v1
kind: HarnessGitopsProjectMapping
metadata:
  labels:
    app.kubernetes.io/name: harness-gitops-agent-operator
    app.kubernetes.io/managed-by: kustomize
  name: harnessgitopsprojectmapping-sample
spec:
  agentRef:
    name: harnessgitopsagent-sample
  appProject: default
