## Append samples of your project ##
resources:
- infrastructure_v1_harnessgitopsagent.yaml
- infrastructure_v1_harnessgitopsprojectmapping.yaml
- infrastructure_v1_harnessgitopsappproject.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
